### ISSUE TITLE
Add support for link events

### ISSUE THREAD

**Issue by jinjaghost** [nitram509/lib-bpmn-engine#141]
Do you have any plan to add support for link events as described here => https://docs.camunda.io/docs/components/modeler/bpmn/link-events/

Regards,

Ken

----

### Acceptance Criteria

- [x] engine supports execution of workflows with link events, according to their meaning
- [x] it's documented in the supported elements sections
- [x] if needed, constraints/caveats are documented
- [x] unit tests exist

**Comment by nitram509** [comment]
Hi Ken,

they look quite trivial to implement.
Could imagine squeezing this into the [v0.3.0](https://github.com/nitram509/lib-bpmn-engine/milestone/3) release.

Is your question purely informal, or do you have a use case for it? (which one? - I would like to learn about usage out there)

Regards
Martin

**Comment by jinjaghost** [comment]
It's about shortcuts to improve readability (like a 'GOTO' for code). As stated in the documentation, there can be multiple catching link events that point to a throwing link event, but the reverse is not compliant. Supporting this element would allow for the creation of higher quality processes.

**Comment by nitram509** [comment]
@jinjaghost 

Ken, support for links has landed ... you might want to look at the current main branch  ;)

Regards
Martin
