### ISSUE TITLE
Can lib-bpmn-engine specify participants via assignment handler?

### ISSUE THREAD

**Issue by schooltech** [nitram509/lib-bpmn-engine#181]
Hi,
For user tasks, it is a common requirement to dynamically assign tasks to users in the business system. In addition to being defined by assignee variables in the process file, the process definition can often define an assignment handler to dynamically assign the people involved when encountering complex logic. Can lib-bpmn-engine specify participants via assignment handler?

Best wishes

**Comment by nitram509** [comment]
> Hi, For user tasks, it is a common requirement to dynamically assign tasks to users in the business system. In addition to being defined by assignee variables in the process file, the process definition can often define an assignment handler to dynamically assign the people involved when encountering complex logic. Can lib-bpmn-engine specify participants via assignment handler?
> 
> Best wishes

Yes, you can do that.
See https://nitram509.github.io/lib-bpmn-engine/implementation-task-handlers/
