### ISSUE TITLE
change task handler to allow input and output parameter as in BPMN

### ISSUE THREAD

**Issue by nitram509** [nitram509/lib-bpmn-engine#2]
bpmn service tasks can be configured with input and output parameters.
currently, the engine can't handle such.
thus, it would be cool to have this feature implemented

**Comment by nitram509** [comment]
must be moved to milestone 0.3, because this requires expression language support

**Comment by lastchiliarch** [comment]
Is this feature developing? It's a useful feature and I'm interested in  helping implement it.

**Comment by nitram509** [comment]
> Is this feature developing? It's a useful feature and I'm interested in helping implement it.

As the label says: "help wanted".
You're very welcome to implement it.

When you're working on it, may I ask you to "assign on this ticket" - just that I and others know you picked it up

**Comment by lastchiliarch** [comment]
I'd like to have a try. 

I'd like to implements this feature  like what camunda behavior (https://docs.camunda.io/docs/components/concepts/variables/), but since  bpmn does not have  expression I  will still use antonmedv/expr  to evaluate expression and set output variable to variableContext.

Do you have any suggestions?

**Comment by nitram509** [comment]
Good point about using 'expr' ... that should work, since it can handle strings etc.

About the variable resolution ... you might can split this feature to
* first only support global/single scope (per instance)
* second introduce scoping, as described on camunda's page you linked.

**Comment by lastchiliarch** [comment]
> 

Agreed, since we don't support sub-process now, I'll support global scope in the first version.
When somebody really needs scope control or supporting sub-process by the engineer,  it's a good time to discuss about introducing scope again.

**Comment by nitram509** [comment]
supported, but with using regular instance scope
