### ISSUE TITLE
Inclusive gateway question.

### ISSUE THREAD

**Issue by magicLian** [nitram509/lib-bpmn-engine#209]
Hello, I noticed a new feature for the inclusive gateway.
But I have a question about it, Why does inclusive gateway only return one flow when it is ok?

https://github.com/nitram509/lib-bpmn-engine/blob/b4c469d241785f8a56ecd82ffc09ec559cb4858b/pkg/bpmn_engine/conditions.go#L46

**Comment by nitram509** [comment]
Hi,

that's right, good catch.
marked as a bug and will provide a fix soon.
thank you

**Comment by nitram509** [comment]
fixed.
