### ISSUE TITLE
Does lib-bpmn-engine  have any plans to add BPMN Subprocess ?

### ISSUE THREAD

**Issue by skandhas** [nitram509/lib-bpmn-engine#23]
Thx. 😊

**Comment by nitram509** [comment]
Hi @skandhas 
thank you for your question.
As of now, the sub-processes are not planned in the milestones, yet.
But I guess this is what you need, I plan it for milestone 0.4.0.

Please, feel free to add more comments or requirements.
There's no formal process of contributing to the roadmap, but I'm quite open to hearing feedback and use cases,
to adopt the milestones according to the needs of the community :)

**Comment by nitram509** [comment]
Planned, see
https://github.com/nitram509/lib-bpmn-engine/issues?q=is%3Aopen+is%3Aissue+milestone%3Av0.4.0

**Comment by nitram509** [comment]
Hi @skandhas,

I hope you're doing well.
There's someone, offering support in implementing this sub-process feature.
May I ask, if you could comment on #24, please.
There's an open question, where I hope you could guide us.
