### ISSUE TITLE
findIntermediateCatchEventsForContinuation always hold the last events

### ISSUE THREAD

**Issue by lastchiliarch** [nitram509/lib-bpmn-engine#29]
findIntermediateCatchEventsForContinuation seems can't handle mulit events, it alwasy catch the last events  when iterating over process.definitions.Process.IntermediateCatchEvent.

code line:
https://github.com/nitram509/lib-bpmn-engine/blob/3dc589633b8b74342b32a95c37c97840c19d7af7/pkg/bpmn_engine/engine.go#L203

I'd like to push a pull requet if possible.

**Comment by nitram509** [comment]
great catch.

PR is very welcome :)

**Comment by nitram509** [comment]
@lastchiliarch thanks to your PR I found one more issue regarding the intermediate catch events.
Yesterday, I did add a test for it ... you might want to have a look if this now works for you.

Thank you for your contribution.

**Comment by lastchiliarch** [comment]
> @lastchiliarch thanks to your PR I found one more issue regarding the intermediate catch events. Yesterday, I did add a test for it ... you might want to have a look if this now works for you.
> 
> Thank you for your contribution.

Thank you very much.  I had tried  but it seems has something wrong.

I had reviewd the code and I think  the problem is  using the MessageRef as map key.

MessageRef may be empty or duplicate sometimes.

When MessageRef  duplicate occurs, the key will point to wrong event.

The bpmn file of ordering example has some duplicate cases like payment-received, payment-received-after-reminder.


```

    <bpmn:intermediateCatchEvent id="payment-received" name="paymend received">
      <bpmn:incoming>Flow_0kax05u</bpmn:incoming>
      <bpmn:outgoing>Flow_1d7iymz</bpmn:outgoing>
      <bpmn:messageEventDefinition id="MessageEventDefinition_1picppw" messageRef="Message_06n2le4" />
    </bpmn:intermediateCatchEvent>

    <bpmn:intermediateCatchEvent id="payment-received-after-reminder" name="payment received">
      <bpmn:incoming>Flow_0d4cjr6</bpmn:incoming>
      <bpmn:outgoing>Flow_0bk30hi</bpmn:outgoing>
      <bpmn:messageEventDefinition id="MessageEventDefinition_1b2el6n" messageRef="Message_06n2le4" />
    </bpmn:intermediateCatchEvent>


```
