### ISSUE TITLE
support for backwards

### ISSUE THREAD

**Issue by lastchiliarch** [nitram509/lib-bpmn-engine#31]
Do we have any plan to support backwards ?

Problem:  Assume that  we allow user to repay the order instead of creating a new order when user choose to refund before confirm-receipt,  it can handle confirm-recepit event and go to send-bill again. 
But it can't handle the next flow becasue of some event had already trigged.  I can't clear or reset the processInfo either.

The order repay flow may sound weird, but it's common for me to desigin flows like that.

I'm trying to design a workflow that user can handle an event then supervisor recheck it.
If the event handled before has some wrong, the supervisor can turn the flow to previous flow again. so that the previous user can handle it again until the supervisor recheck pass.

At now, I can't archive this goal graceful without backwards support. 
Do you have some suggestions?

![image](https://user-images.githubusercontent.com/3797268/187198599-1052d42b-ced3-4ac7-a5d1-f24b484e8a94.png)

**Comment by nitram509** [comment]
Hi @lastchiliarch 
if I got you right, then you want to go backward, like in a loop?
I mean basically, what does this loop BPMN shown below?

That is likely not supported in the current version ... but I will think about, how to implement it 👍 

Thank you for your feedback.
Also, PRs are always welcome :)

<img width="450" alt="Screenshot 2022-08-29 at 14 47 04" src="https://user-images.githubusercontent.com/1189394/187204604-81dd6360-5bca-4e27-b2e4-23c1555db181.png">

**Comment by lastchiliarch** [comment]
Yes,  that's what i want.   I'm new to bpmn so the implement is diffcult for me . But I'd like to help doing a part of job of this one or anything I can.

**Comment by nitram509** [comment]
Hi @lastchiliarch 

I've implemented a test, that show "backwards" works in this simple loop example above.
See https://github.com/nitram509/lib-bpmn-engine/blob/532d2d18be8253b71d643fabd679d48e2170076a/pkg/bpmn_engine/engine_jobs_test.go#L23

**Comment by nitram509** [comment]
I re-read your initial post and I have to admit, I don't understand your business requirement.
What I can say, BPMN does not support "reset" == if you design some condition after the "confirm receipt",
the bpmn flow will continue a second round.

This is likeley not what you want in business, I guess.
I would rather suggest, to model a separate BPMN process for refunding.

 A typical refind process could look like:
1. find existing order process
2. cancel existing order process (lib-bpmn-engine does not support cancelling yet, but BPMN itself is desgined for that)
3. validate refund conditions
4. subtract refund fees
5. make payment order, so the user gets its money back

The benefit of having two processes are
* more transparency, what was happen, when you "link" the processes by their keys
* easier to understand
* easier to distribute

How does this resonate with you?

**Comment by nitram509** [comment]
Got your point ... there seems to be another bug, working on it.

**Comment by nitram509** [comment]
Hi siconghuang,

I did just a minute ago post some fixes, which were still present, for the bug mentioned above.

I did some modifications as well, to make the code + BPMN more simple.
* IF there's just a single intermediate message catch event in the flow, you don't need a event gateway in front neither an exclusive gateway afterward
* you should not send events from inside a service task
   * that might be technically possible, but is not necessary code, the engine does the process execution for you
   * it's very difficult to read/understand such code
* from your example, I think it would be more convenient to have the #41 implemented, BUT as you can see, the "validate supervisor result" task takes care of updating the proper variable within the instance.

![Screenshot 2022-09-07 at 21 41 55](https://user-images.githubusercontent.com/1189394/188963553-562cef8b-4979-434a-8d5f-88dc5bf09ee8.png)

```go
import (
	"fmt"
	"github.com/corbym/gocrest/is"
	"github.com/corbym/gocrest/then"
	"github.com/nitram509/lib-bpmn-engine/pkg/bpmn_engine"
	"github.com/nitram509/lib-bpmn-engine/pkg/spec/BPMN20/process_instance"
	"log"
	"testing"
)

var (
	bpmnEngine = bpmn_engine.New("auth_apply")
	process    *bpmn_engine.ProcessInfo
	instance   *bpmn_engine.ProcessInstanceInfo
)

// these test-* variables do mimic/simulate external events or manual actions
var testAuditAttempt = 0

const BEIJING = "Beijing"
const LONDON = "London"

func Test_apply_auth_loop(t *testing.T) {
	// setup
	var err error
	process, err = bpmnEngine.LoadFromFile("auth_apply.bpmn")
	bpmnEngine.AddTaskHandler("apply_auth", applyAuth)
	bpmnEngine.AddTaskHandler("audit", audit)
	bpmnEngine.AddTaskHandler("notify_supervisor", notifySupervisor)
	bpmnEngine.AddTaskHandler("validate_supervisor_result", validateSupervisorResult)
	bpmnEngine.AddTaskHandler("prove_auth", proveAuth)

	instance, err = bpmnEngine.CreateInstance(process.ProcessKey, nil)
	fmt.Println(err)

	// HINT: BPMN spec allows message published with variables, but the engine does not (yet) support that
	// so ideally, bpmnEngine.PublishEventForInstance() should support variables to pass in

	bpmnEngine.RunOrContinueInstance(instance.GetInstanceKey())
	then.AssertThat(t, instance.GetVariable("city"), is.EqualTo(LONDON))

	bpmnEngine.PublishEventForInstance(instance.GetInstanceKey(), "supervision_reported") // first response from supervisor
	bpmnEngine.RunOrContinueInstance(instance.GetInstanceKey())                           // will loop back and executes the audit as well, stops because of second intermediate catch event

	bpmnEngine.PublishEventForInstance(instance.GetInstanceKey(), "supervision_reported") // first response from supervisor
	bpmnEngine.RunOrContinueInstance(instance.GetInstanceKey())                           // will catch up the second event and exits the instance
	then.AssertThat(t, instance.GetVariable("city"), is.EqualTo(BEIJING))

	then.AssertThat(t, instance.GetState(), is.EqualTo(process_instance.COMPLETED))
}

func validateSupervisorResult(job bpmn_engine.ActivatedJob) {
	reAudit := testAuditAttempt <= 1 // for testing purpose, the first attempt is always wrong
	log.Println(fmt.Sprintf("validateSupervisorResult, reAudit=%t", reAudit))
	job.SetVariable("reAudit", reAudit)
	job.Complete()
}

func applyAuth(job bpmn_engine.ActivatedJob) {
	log.Println("start to applyAuth")
	job.Complete()
}

func audit(job bpmn_engine.ActivatedJob) {
	log.Println("start to audit")
	if testAuditAttempt < 1 {
		job.SetVariable("city", LONDON)
	} else {
		job.SetVariable("city", BEIJING)
	}
	testAuditAttempt = testAuditAttempt + 1 // change audit result for next time
	job.Complete()
}

func proveAuth(job bpmn_engine.ActivatedJob) {
	log.Println("start to proveAuth")
	job.Complete()
}

func notifySupervisor(job bpmn_engine.ActivatedJob) {
	city := job.GetVariable("city").(string)
	log.Println(fmt.Sprintf("start to notifySupervisor; city=%s", city))
	job.Complete()
}

```

BPMN Source ...
[auth_apply.bpmn.txt](https://github.com/nitram509/lib-bpmn-engine/files/9509153/auth_apply.bpmn.txt)

**Comment by nitram509** [comment]
@lastchiliarch does my above proposal help?

**Comment by lastchiliarch** [comment]
> @lastchiliarch does my above proposal help?

Thanks for your help and hard work. It's diffcult for  the "validate supervisor result" task to control the flow, seems message event could be  a more graceful approach.
