### ISSUE TITLE
 Does lib-bpmn-engine plan to support user tasks?

### ISSUE THREAD

**Issue by schooltech** [nitram509/lib-bpmn-engine#32]
I found that lib-bpmn-engine currently only supports service tasks. Does lib-bpmn-engine plan to support user tasks?

**Comment by nitram509** [comment]
Hi,

good question ... currently I don't have it planned in the roadmap. Obviously, pull requests are more than welcome ;)

May I ask, how would you expect to use it?
And how would you expect it differs from service tasks?

The reason I'm asking ... when its just about supporting the element and acting similar/equal to service tasks that might be just a quick change.

**Comment by schooltech** [comment]
In bpmn 2.0, tasks are divided into user task, service task, send task, send task, script task, etc. We usually use service task to deal with nodes whose state changes instantaneously, and then the process goes to the next node without waiting, while The user task is used to process the node that is attended, and wait until the node is completed. Usually, the requirement of the workflow requires manual participation. Of course, I hope lib-bpmn-engine can meet this requirement.
Thanks for your excellent work.

**Comment by nitram509** [comment]
Thank you for your comments.

On the roadmap, I also plan (de-)serialization of the engine's internal state. With this, it would be possible to persist paused processes into a DB. I consider that an important feature.

May I ask about your view: would you consider user tasks support more important for you than the serialization one?

**Comment by schooltech** [comment]
Thank you for your reply, I think both of these features are very important for a bpmn 2.0 compliant workflow and for the lib bpmn engine to be widely recognized and used. Thanks for your great work and hope the lib bpmn engine keeps getting better and better.
