### ISSUE TITLE
support adding variables along with publishing messages

### ISSUE THREAD

**Issue by nitram509** [nitram509/lib-bpmn-engine#41]
## motivation

As documented, https://docs.camunda.io/docs/components/modeler/bpmn/message-events/
when publishing a message, variables shall be possible to be added

## acceptance criteria

- [x] documentation exists & examples are updated
- [x] variables can be passed with message publishing
- [ ] exciter: "variable mapping", as defined in Camunda's documentation works as well

hint: "exciter" means this is not required to complete/finish this issue, but would be really awesome, if present/included
all other criteria are mandatory

**Comment by lastchiliarch** [comment]
I'd like to do this.
