### ISSUE TITLE
improve documentation for supported elements

### ISSUE THREAD

**Issue by nitram509** [nitram509/lib-bpmn-engine#45]
## motivation

the bullet items of supported elements is quite compact and not easy to digest for beginners.
so, the main idea is to improve documentation for beginners

## acceptance criteria

- [ ] pictures/symbols for each elements are shown
- [ ] short element description is available
- [ ] relevant caveats (compared to other engines) are described

**Comment by rhzs** [comment]
Hi @nitram509 , what are the current supported elements?

**Comment by nitram509** [comment]
@rhzs just have a look here
https://nitram509.github.io/lib-bpmn-engine/supported-elements/
source:
https://github.com/nitram509/lib-bpmn-engine/blob/main/docs/supported-elements.md

I can support with the last acceptance criteria ;)
