### ISSUE TITLE
rework job.SetVariable() only when calling complete() or fail()

### ISSUE THREAD

**Issue by nitram509** [nitram509/lib-bpmn-engine#55]
## motivation

- don't allow altering process instance state, when job's are in-flight
- align with zeebe go client

**Comment by ryzheboka** [comment]
Hi @nitram509, can I try to work on this issue?

**Comment by nitram509** [comment]
@ryzheboka 
Hi Elena,
of course, you can ... just be aware, there's another PR for that already.
That said, I'm not fully satisfied with the existing PR yet, because there are some naming/wording issues, and I haven't found the time yet to give proper feedback.

What solution do you have in mind?
And how would it differ from the existing PR?

**Comment by nitram509** [comment]
note: relates to #48

**Comment by nitram509** [comment]
@ryzheboka
Hi Elena, I did implement variable scopes for jobs ... does this fit your use case (and so the reason for this issue is solved?)

**Comment by ryzheboka** [comment]
Hi @nitram509 , my bad, I didn't see the existing PR before commenting. I didn't have a use case in mind other than "don't allow altering process instance state, when job's are in-flight" as described above. Adding variable scopes for jobs makes sense to me regarding this issue. I wanted to try to solve it in order to get familiar with the project. 

Can you recommend another issue for me to try as beginner in bpmn? Or would you recommend me to gain more experience and try easier projects first?

**Comment by nitram509** [comment]
Hi @ryzheboka 
thank you for your interest in this project.
Indeed, the refactoring of the variable scope was a relatively beginner-friendly issue.

There are some ideas, which come to my mind and I will share them below.
They are not ordered and depend on how much familiar you're with Go as well. 

* #44 - it does follow an already implemented concept, that might simplify the entry-level
* #38 - looks simple as well since prior work on error types was done
* add an example app, to showcase expression language support, to be added to "advanced examples" within the documentation
* there are also some "TODO" comments in the code, which would be great to solve

I would be very glad to discuss further with you.
Please, feel free to get in touch via email, as you see in my commit messages.

**Comment by nitram509** [comment]
@ryzheboka 
Hi Elena, in case you're still interested to contribute ... I did create some more issues and marked them "good first issue" :)

Regards and Merry Christmas
Martin

**Comment by ryzheboka** [comment]
@nitram509 
Hi Martin, thank you a lot! I will have a look at the "good first issue" issues and see which of them is the most understandable for me.

Merry Christmas to you too!
Elena
