### ISSUE TITLE
tried in private production project?

### ISSUE THREAD

**Issue by kstan79** [nitram509/lib-bpmn-engine#60]
This project look interesting, tried in production use case?

**Comment by nitram509** [comment]
Hi @kstan79 ,

on your question, I'm not aware of any in-production use of this library.
As stated in the readme file, I would not recommend production use for now, without your own testing
(I mean, does it fit for/with your workflows?)

The library will change its API over the next releases, to incorporate some required features.
I would say basic BPMN compliance is good - but there are definitely some BPMN features like Exception handling missing.
Such I do see required for production use.

Also, the library does not do housekeeping of its resources. E.g. internal maps will grow over time and consume your memory. I also would see such as another requirement for robust production use. 

Regards
Martin
