### ISSUE TITLE
bpmnEngine.NewTaskHandler undefined

### ISSUE THREAD

**Issue by kstan79** [nitram509/lib-bpmn-engine#61]
Im trying this library follow guide https://nitram509.github.io/lib-bpmn-engine/getting-started, it gave:
```
./main.go:18:13: bpmnEngine.NewTaskHandler undefined (type bpmn_engine.BpmnEngineState has no field or method NewTaskHandler)
```

**Comment by nitram509** [comment]
> im checkout latest master version.

That's strange.
The ```NewTaskHandler().Assignee()...``` function in **main** branch is looking as shown in the previous comment.
I wonder how your code ```AddTaskHandler("hello-world", printContextHandler)``` can even compile without error?

There must be some difference. What do we oversee?

**Comment by kstan79** [comment]
oh, i know the reason. most probably i'm create new go project with direct import remote package.  no check out source code

**Comment by eriknyk** [comment]
@kstan79  for latest `0.3.0-beta2`

```
go get github.com/nitram509/lib-bpmn-engine/pkg/bpmn_engine@v0.3.0-beta2
```

Should enough!
