### ISSUE TITLE
Rework engine-name to be optional

### ISSUE THREAD

**Issue by nitram509** [nitram509/lib-bpmn-engine#71]
## motivation

the name of the engine should be optional

hint: engine instances are supposed to have a name, to differentiate multiple instances - e.g. during logging.

## acceptance criteria

- [ ] the name for the bpmn engine is optional, means an engine can be created straight, without providing a name
- [ ] a default name per engine is created, when no explicit name is provided

**Comment by ryzheboka** [comment]
@nitram509 
Hi Martin :) can I try to work on this issue?

**Comment by nitram509** [comment]
@ryzheboka you're welcome, go for it.

**Comment by nitram509** [comment]
I marked this one with label "WiP" == Work in Progress and assigned you.

**Comment by jinjaghost** [comment]
This can be close since it's now fully supported.

**Comment by nitram509** [comment]
Thank you @jinjaghost for your support 👍 🚀 

I picked up your changes and reworked to make default instances without a name,
and only if someone wants to set a name, then there's an alternative initializer method.
I guess majority of users don't need a named engine, hence the adoption.
